### ISSUE TITLE
Support for 6.7.0 U2

### ISSUE THREAD

**Issue by levickij** [lamw/ax88179_178a-esxi#1]
Would it possible to provide an update of the VIB to support 6.7.0 U2?

![image](https://user-images.githubusercontent.com/51518633/85135492-1647be00-b236-11ea-9893-167df4cecf8b.png)

Having installed the 6.5 driver, it appears that this driver will not work with 6.7.0 U2.

![image](https://user-images.githubusercontent.com/51518633/85135446-0203c100-b236-11ea-81ec-3e85e2109955.png)

Thanks in advance.

**Comment by lamw** [comment]
Please use the official VMware Fling https://flings.vmware.com/usb-network-native-driver-for-esxi

**Comment by levickij** [comment]
Thankyou.
